import { Poppins } from "next/font/google";
import MainLayout from '../../src/app/components/MainLayout';
import "./globals.css";

const poppins = Poppins({
  weight: ['400','500','600','700','900' ],
  subsets: ["latin"], 
  variable: "--font-poppins", 
});

export const metadata = {
  title: "CheckIo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}