

import { Poppins } from "next/font/google";
import MainLayout from '../../src/app/components/MainLayout';
import "./globals.css";

// Import Poppins font properly
const poppins = Poppins({
  weight: ['400','500','600','700','900' ], // Specify the font weights you need
  subsets: ["latin"], // Use Latin subset for compatibility
  variable: "--font-poppins", // CSS variable name
});

export const metadata = {
  title: "CheckIo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}